/*
 * lthn API
 *
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Lthn.Api.Client;
using Lthn.Api.Model;

namespace Lthn.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRunnerApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List configured runner model routes
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetV1RunnerModels200Response</returns>
        GetV1RunnerModels200Response GetV1RunnerModels();

        /// <summary>
        /// List configured runner model routes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetV1RunnerModels200Response</returns>
        ApiResponse<GetV1RunnerModels200Response> GetV1RunnerModelsWithHttpInfo();
        /// <summary>
        /// Multi-turn chat completion
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerChatRequest"></param>
        /// <returns>PostV1RunnerChat200Response</returns>
        PostV1RunnerChat200Response PostV1RunnerChat(PostV1RunnerChatRequest postV1RunnerChatRequest);

        /// <summary>
        /// Multi-turn chat completion
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerChatRequest"></param>
        /// <returns>ApiResponse of PostV1RunnerChat200Response</returns>
        ApiResponse<PostV1RunnerChat200Response> PostV1RunnerChatWithHttpInfo(PostV1RunnerChatRequest postV1RunnerChatRequest);
        /// <summary>
        /// Single-prompt generation
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerGenerateRequest"></param>
        /// <returns>PostV1RunnerChat200Response</returns>
        PostV1RunnerChat200Response PostV1RunnerGenerate(PostV1RunnerGenerateRequest postV1RunnerGenerateRequest);

        /// <summary>
        /// Single-prompt generation
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerGenerateRequest"></param>
        /// <returns>ApiResponse of PostV1RunnerChat200Response</returns>
        ApiResponse<PostV1RunnerChat200Response> PostV1RunnerGenerateWithHttpInfo(PostV1RunnerGenerateRequest postV1RunnerGenerateRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRunnerApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// List configured runner model routes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetV1RunnerModels200Response</returns>
        System.Threading.Tasks.Task<GetV1RunnerModels200Response> GetV1RunnerModelsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List configured runner model routes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetV1RunnerModels200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetV1RunnerModels200Response>> GetV1RunnerModelsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Multi-turn chat completion
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerChatRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PostV1RunnerChat200Response</returns>
        System.Threading.Tasks.Task<PostV1RunnerChat200Response> PostV1RunnerChatAsync(PostV1RunnerChatRequest postV1RunnerChatRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Multi-turn chat completion
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerChatRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PostV1RunnerChat200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<PostV1RunnerChat200Response>> PostV1RunnerChatWithHttpInfoAsync(PostV1RunnerChatRequest postV1RunnerChatRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Single-prompt generation
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerGenerateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PostV1RunnerChat200Response</returns>
        System.Threading.Tasks.Task<PostV1RunnerChat200Response> PostV1RunnerGenerateAsync(PostV1RunnerGenerateRequest postV1RunnerGenerateRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Single-prompt generation
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerGenerateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PostV1RunnerChat200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<PostV1RunnerChat200Response>> PostV1RunnerGenerateWithHttpInfoAsync(PostV1RunnerGenerateRequest postV1RunnerGenerateRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRunnerApi : IRunnerApiSync, IRunnerApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RunnerApi : IDisposable, IRunnerApi
    {
        private Lthn.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RunnerApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public RunnerApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunnerApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public RunnerApi(string basePath)
        {
            this.Configuration = Lthn.Api.Client.Configuration.MergeConfigurations(
                Lthn.Api.Client.GlobalConfiguration.Instance,
                new Lthn.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Lthn.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Lthn.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunnerApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public RunnerApi(Lthn.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Lthn.Api.Client.Configuration.MergeConfigurations(
                Lthn.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Lthn.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Lthn.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunnerApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RunnerApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunnerApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RunnerApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Lthn.Api.Client.Configuration.MergeConfigurations(
                Lthn.Api.Client.GlobalConfiguration.Instance,
                new Lthn.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Lthn.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Lthn.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunnerApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public RunnerApi(HttpClient client, Lthn.Api.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Lthn.Api.Client.Configuration.MergeConfigurations(
                Lthn.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Lthn.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Lthn.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RunnerApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public RunnerApi(Lthn.Api.Client.ISynchronousClient client, Lthn.Api.Client.IAsynchronousClient asyncClient, Lthn.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Lthn.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Lthn.Api.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Lthn.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Lthn.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Lthn.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Lthn.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// List configured runner model routes 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetV1RunnerModels200Response</returns>
        public GetV1RunnerModels200Response GetV1RunnerModels()
        {
            Lthn.Api.Client.ApiResponse<GetV1RunnerModels200Response> localVarResponse = GetV1RunnerModelsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List configured runner model routes 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetV1RunnerModels200Response</returns>
        public Lthn.Api.Client.ApiResponse<GetV1RunnerModels200Response> GetV1RunnerModelsWithHttpInfo()
        {
            Lthn.Api.Client.RequestOptions localVarRequestOptions = new Lthn.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Lthn.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Lthn.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetV1RunnerModels200Response>("/v1/runner/models", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetV1RunnerModels", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List configured runner model routes 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetV1RunnerModels200Response</returns>
        public async System.Threading.Tasks.Task<GetV1RunnerModels200Response> GetV1RunnerModelsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            Lthn.Api.Client.ApiResponse<GetV1RunnerModels200Response> localVarResponse = await GetV1RunnerModelsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List configured runner model routes 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetV1RunnerModels200Response)</returns>
        public async System.Threading.Tasks.Task<Lthn.Api.Client.ApiResponse<GetV1RunnerModels200Response>> GetV1RunnerModelsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Lthn.Api.Client.RequestOptions localVarRequestOptions = new Lthn.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Lthn.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Lthn.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetV1RunnerModels200Response>("/v1/runner/models", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetV1RunnerModels", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Multi-turn chat completion 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerChatRequest"></param>
        /// <returns>PostV1RunnerChat200Response</returns>
        public PostV1RunnerChat200Response PostV1RunnerChat(PostV1RunnerChatRequest postV1RunnerChatRequest)
        {
            Lthn.Api.Client.ApiResponse<PostV1RunnerChat200Response> localVarResponse = PostV1RunnerChatWithHttpInfo(postV1RunnerChatRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Multi-turn chat completion 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerChatRequest"></param>
        /// <returns>ApiResponse of PostV1RunnerChat200Response</returns>
        public Lthn.Api.Client.ApiResponse<PostV1RunnerChat200Response> PostV1RunnerChatWithHttpInfo(PostV1RunnerChatRequest postV1RunnerChatRequest)
        {
            // verify the required parameter 'postV1RunnerChatRequest' is set
            if (postV1RunnerChatRequest == null)
                throw new Lthn.Api.Client.ApiException(400, "Missing required parameter 'postV1RunnerChatRequest' when calling RunnerApi->PostV1RunnerChat");

            Lthn.Api.Client.RequestOptions localVarRequestOptions = new Lthn.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Lthn.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Lthn.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = postV1RunnerChatRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PostV1RunnerChat200Response>("/v1/runner/chat", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostV1RunnerChat", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Multi-turn chat completion 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerChatRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PostV1RunnerChat200Response</returns>
        public async System.Threading.Tasks.Task<PostV1RunnerChat200Response> PostV1RunnerChatAsync(PostV1RunnerChatRequest postV1RunnerChatRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Lthn.Api.Client.ApiResponse<PostV1RunnerChat200Response> localVarResponse = await PostV1RunnerChatWithHttpInfoAsync(postV1RunnerChatRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Multi-turn chat completion 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerChatRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PostV1RunnerChat200Response)</returns>
        public async System.Threading.Tasks.Task<Lthn.Api.Client.ApiResponse<PostV1RunnerChat200Response>> PostV1RunnerChatWithHttpInfoAsync(PostV1RunnerChatRequest postV1RunnerChatRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'postV1RunnerChatRequest' is set
            if (postV1RunnerChatRequest == null)
                throw new Lthn.Api.Client.ApiException(400, "Missing required parameter 'postV1RunnerChatRequest' when calling RunnerApi->PostV1RunnerChat");


            Lthn.Api.Client.RequestOptions localVarRequestOptions = new Lthn.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Lthn.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Lthn.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = postV1RunnerChatRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PostV1RunnerChat200Response>("/v1/runner/chat", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostV1RunnerChat", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Single-prompt generation 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerGenerateRequest"></param>
        /// <returns>PostV1RunnerChat200Response</returns>
        public PostV1RunnerChat200Response PostV1RunnerGenerate(PostV1RunnerGenerateRequest postV1RunnerGenerateRequest)
        {
            Lthn.Api.Client.ApiResponse<PostV1RunnerChat200Response> localVarResponse = PostV1RunnerGenerateWithHttpInfo(postV1RunnerGenerateRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Single-prompt generation 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerGenerateRequest"></param>
        /// <returns>ApiResponse of PostV1RunnerChat200Response</returns>
        public Lthn.Api.Client.ApiResponse<PostV1RunnerChat200Response> PostV1RunnerGenerateWithHttpInfo(PostV1RunnerGenerateRequest postV1RunnerGenerateRequest)
        {
            // verify the required parameter 'postV1RunnerGenerateRequest' is set
            if (postV1RunnerGenerateRequest == null)
                throw new Lthn.Api.Client.ApiException(400, "Missing required parameter 'postV1RunnerGenerateRequest' when calling RunnerApi->PostV1RunnerGenerate");

            Lthn.Api.Client.RequestOptions localVarRequestOptions = new Lthn.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Lthn.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Lthn.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = postV1RunnerGenerateRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PostV1RunnerChat200Response>("/v1/runner/generate", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostV1RunnerGenerate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Single-prompt generation 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerGenerateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PostV1RunnerChat200Response</returns>
        public async System.Threading.Tasks.Task<PostV1RunnerChat200Response> PostV1RunnerGenerateAsync(PostV1RunnerGenerateRequest postV1RunnerGenerateRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Lthn.Api.Client.ApiResponse<PostV1RunnerChat200Response> localVarResponse = await PostV1RunnerGenerateWithHttpInfoAsync(postV1RunnerGenerateRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Single-prompt generation 
        /// </summary>
        /// <exception cref="Lthn.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="postV1RunnerGenerateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PostV1RunnerChat200Response)</returns>
        public async System.Threading.Tasks.Task<Lthn.Api.Client.ApiResponse<PostV1RunnerChat200Response>> PostV1RunnerGenerateWithHttpInfoAsync(PostV1RunnerGenerateRequest postV1RunnerGenerateRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'postV1RunnerGenerateRequest' is set
            if (postV1RunnerGenerateRequest == null)
                throw new Lthn.Api.Client.ApiException(400, "Missing required parameter 'postV1RunnerGenerateRequest' when calling RunnerApi->PostV1RunnerGenerate");


            Lthn.Api.Client.RequestOptions localVarRequestOptions = new Lthn.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Lthn.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Lthn.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = postV1RunnerGenerateRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PostV1RunnerChat200Response>("/v1/runner/generate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostV1RunnerGenerate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
