/*
 * lthn API
 *
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Lthn.Api.Client.FileParameter;
using OpenAPIDateConverter = Lthn.Api.Client.OpenAPIDateConverter;

namespace Lthn.Api.Model
{
    /// <summary>
    /// PostV1RunnerGenerateRequest
    /// </summary>
    [DataContract(Name = "post_v1_runner_generate_request")]
    public partial class PostV1RunnerGenerateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostV1RunnerGenerateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PostV1RunnerGenerateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PostV1RunnerGenerateRequest" /> class.
        /// </summary>
        /// <param name="prompt">prompt (required).</param>
        public PostV1RunnerGenerateRequest(string prompt = default)
        {
            // to ensure "prompt" is required (not null)
            if (prompt == null)
            {
                throw new ArgumentNullException("prompt is a required property for PostV1RunnerGenerateRequest and cannot be null");
            }
            this.Prompt = prompt;
        }

        /// <summary>
        /// Gets or Sets Prompt
        /// </summary>
        [DataMember(Name = "prompt", IsRequired = true, EmitDefaultValue = true)]
        public string Prompt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostV1RunnerGenerateRequest {\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
